[package]
name = "m0f-ort-ocr"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.10"
ndarray = "0.17.2"
ort = { version = "2.0.0-rc.13", default-features = false, features = ["load-dynamic"] }
